### ISSUE TITLE
Update from version 21.4.3 Failed

### ISSUE THREAD

**Issue by aalex954** [Atomicorp/gvm#61]
CentOS8 Stream

Since updating (7/24) I receive the error message: 

`Could not connect to Scanner when running scans. `

gvmd.service is running
gsad.service is running
ospd-openvas.service says activating

`sudo gvmd --get-scanners` returns nothing

/var/log/gvm/gvmd.log 

```
Greenbone Vulnerability Manager version 21.4.5 (DB revision 242)
md manage:   INFO:2022-07-24 04h17.43 utc:122201:    Getting scanners.
md manage:WARNING:2022-07-24 04h17.43 utc:122201: sql_open: PQconnectPoll failed
md manage:WARNING:2022-07-24 04h17.43 utc:122201: sql_open: PQerrorMessage (conn): FATAL:  role "root" does not exist
md manage:WARNING:2022-07-24 04h17.43 utc:122201: init_manage_open_db: sql_open failed
md manage:WARNING:2022-07-24 04h17.49 UTC:122203: osp_scanner_feed_version: failed to connect to /var/run/ospd/ospd-openvas.sock
```

Any suggestions?

**Comment by b-keller** [comment]
Hi,

Same problem with RockyLinux 8.6, since last update, the osp-openvas.service hang

```
juil. 26 11:48:47 s029 systemd[1]: Started Job that runs the ospd-openvas daemon.
juil. 26 11:48:48 s029 ospd-openvas[1902]: Traceback (most recent call last):
juil. 26 11:48:48 s029 ospd-openvas[1902]:   File "/opt/atomicorp/bin/ospd-openvas", line 5, in <module>
juil. 26 11:48:48 s029 ospd-openvas[1902]:     from ospd_openvas.daemon import main
juil. 26 11:48:48 s029 ospd-openvas[1902]:   File "/opt/atomicorp/lib/python3.8/site-packages/ospd_openvas/daemon.py", line 33, in <module>
juil. 26 11:48:48 s029 ospd-openvas[1902]:     from lxml.etree import tostring, SubElement, Element
juil. 26 11:48:48 s029 ospd-openvas[1902]: ModuleNotFoundError: No module named 'lxml.etree'
juil. 26 11:48:48 s029 systemd[1]: ospd-openvas.service: Main process exited, code=exited, status=1/FAILURE
juil. 26 11:48:48 s029 systemd[1]: ospd-openvas.service: Failed with result 'exit-code'.
```


problem with python module lxml.etree ?

**Comment by b-keller** [comment]
So,

I don't understand why, but in my system, there was python 3.6.x et 3.8.x installed
And the default one was 3.6.x
```
# dnf list installed python3?
Paquets installés
python36.x86_64                                         3.6.8-38.module+el8.5.0+671+195e4563                                          @appstream
python38.x86_64                                         3.8.12-1.module+el8.6.0+794+eba84017                                          @appstream
```

so I do this
```
# alternatives --set python /usr/bin/python3.8
# alternatives --set python3 /usr/bin/python3.8
# python -V
Python 3.8.12
# python3 -V
Python 3.8.12
# systemctl restart ospd-openvas
# systemctl status ospd-openvas.service
● ospd-openvas.service - Job that runs the ospd-openvas daemon
   Loaded: loaded (/usr/lib/systemd/system/ospd-openvas.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2022-07-26 13:07:47 CEST; 56s ago
```

and scanner is running
```
# sudo -u gvm gvmd --get-scanners
08b69003-5fc2-4037-a479-93b440211c73  OpenVAS  /run/ospd/ospd-openvas.sock  0  OpenVAS Default
6acd0832-df90-11e4-b9d5-28d24461215b  CVE    0  CVE
# sudo -u gvm gvmd --verify-scanner 08b69003-5fc2-4037-a479-93b440211c73
Scanner version: OpenVAS 21.4.4.
```

**Comment by atomicturtle** [comment]
It is absolutely pinned to specific versions of python, for EL8 this is going to be python3.8 (on fc37 its 3.11), so in general Id say if you are building an GVM appliance do it on a dedicated system.
