### ISSUE TITLE
 OpenVAS Scan failed (RHEL 8)

### ISSUE THREAD

**Issue by HarunaMurata** [Atomicorp/gvm#64]
I have OpenVAS 21.4.0 installed on Red Hat Enterprise Linux 8.
I have been running SCAN regularly, but half a year ago it suddenly became impossible to SCAN.
The thing that comes to mind is an update of Red Hat Enterprise Linux 8.
The logs show the following.
Manual scans also resulted in the same error.
Please let me how to isolate the problem.

<ospd-scanner.log>
    scan_info = self.data_manager.dict()  # type: Dict
  File "/usr/lib64/python3.8/multiprocessing/managers.py", line 740, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib64/python3.8/multiprocessing/managers.py", line 623, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 506, in Client
    c = SocketClient(address)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 634, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
OSPD[1160] 2022-12-01 19:25:50,403: ERROR: (ospd.ospd) While handling client command:
Traceback (most recent call last):
  File "/opt/atomicorp/lib/python3.8/site-packages/ospd-21.4.0-py3.8.egg/ospd/ospd.py", line 506, in handle_client_stream
    self.handle_command(data, stream)
  File "/opt/atomicorp/lib/python3.8/site-packages/ospd-21.4.0-py3.8.egg/ospd/ospd.py", line 1246, in handle_command
    response = command.handle_xml(tree)
  File "/opt/atomicorp/lib/python3.8/site-packages/ospd-21.4.0-py3.8.egg/ospd/command/command.py", line 575, in handle_xml
    scan_id = self._daemon.create_scan(
  File "/opt/atomicorp/lib/python3.8/site-packages/ospd-21.4.0-py3.8.egg/ospd/ospd.py", line 1410, in create_scan
    return self.scan_collection.create_scan(
  File "/opt/atomicorp/lib/python3.8/site-packages/ospd-21.4.0-py3.8.egg/ospd/scan.py", line 323, in create_scan
    scan_info = self.data_manager.dict()  # type: Dict
  File "/usr/lib64/python3.8/multiprocessing/managers.py", line 740, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib64/python3.8/multiprocessing/managers.py", line 623, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 506, in Client
    c = SocketClient(address)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 634, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by HarunaMurata** [comment]
This month's regular scan also failed with the same error.
Is anyone else having the same problem?

**Comment by atomicturtle** [comment]
There are some updates coming up in the atomic-testing channel, do you think you can try these out to see if they cover it? You can upgrade with:

yum --enablerepo=atomic-testing update

**Comment by atomicturtle** [comment]
These packages have been published to the atomic repo, let us know if you're still having a problem otherwise we'll close this one out shortly

**Comment by HarunaMurata** [comment]
Thanks for your update.
I will update the package as suggested.
However, when I run the command I get the following error.
***
  yum --enablerepo=atomic-testing update
  Updating Subscription Management repositories.
  Error: Unknown repo: 'atomic-testing'
***
I don't know the cause of the error, is it a problem in our environment?
