### ISSUE TITLE
GVM 22.4.0 error when I do a scan

### ISSUE THREAD

**Issue by Neflyte49** [Atomicorp/gvm#69]
Hi I have gvm 22.4.0 on Rocky Linux 8 and sudenly when I tried to do a scan ospd expell this error:
==> ospd-scanner.log <==
OSPD[873] 2023-06-12 20:38:47,432: ERROR: (ospd.ospd) While handling client command:
Traceback (most recent call last):
  File "/opt/atomicorp/lib/python3.8/site-packages/ospd/ospd.py", line 558, in handle_client_stream
    self.handle_command(data, stream)
  File "/opt/atomicorp/lib/python3.8/site-packages/ospd/ospd.py", line 1077, in handle_command
    response = command.handle_xml(tree)
  File "/opt/atomicorp/lib/python3.8/site-packages/ospd/command/command.py", line 617, in handle_xml
    scan_id = self._daemon.create_scan(
  File "/opt/atomicorp/lib/python3.8/site-packages/ospd/ospd.py", line 1255, in create_scan
    return self.scan_collection.create_scan(
  File "/opt/atomicorp/lib/python3.8/site-packages/ospd/scan.py", line 323, in create_scan
    scan_info = self.data_manager.dict()  # type: Dict
  File "/usr/lib64/python3.8/multiprocessing/managers.py", line 740, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib64/python3.8/multiprocessing/managers.py", line 623, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 506, in Client
    c = SocketClient(address)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 634, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

Can you help me?

Thanks in advance. 

Greetings

**Comment by atomicturtle** [comment]
Yeah I can repeat this, and related some of these python changes also broke certbot from lets-encrypt.

**Comment by Neflyte49** [comment]
Any mitigation procedure?

Greetings

**Comment by ChenrySecmon** [comment]
I've been experiencing the same error for a while now. The scan interrupts at 0%, and ospd.logs show this error. Have you found a solution? I hope I don't have to reinstall everything.

**Comment by przemo539** [comment]
I found solution which work in my environment.

Step by step:
1.  dnf update
2.  dnf --enablerepo=atomic-testing update
3. gvm-setup
4.  mkdir /run/gvmd/
5.  chown gvm:gvm gvmd
6. /bin/systemctl stop gvmd.service
/bin/systemctl stop gsad.service
/bin/systemctl stop ospd-openvas.service
8. su gvm
9. gvmd --migrate
10. exit
11. /bin/systemctl start gvmd.service
/bin/systemctl start gsad.service
/bin/systemctl start ospd-openvas.service

I'm not sure which step repaired instance but probably creation  directory gvmd in /run space.
